/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jarrodquan.shack.mysql.adapter.port

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
