spring:
  profiles:
    active: dev
  application:
    name: shack-web-adapter
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 10GB
      location: ${user.home}/.shack/upload
logging:
  path: ${user.dir}
  file: shack.log