/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jarrodquan.shack.adapter.repo.mysql

import kotlin.test.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
    }
}
