/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jarrodquan.shack.application.domain

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
